### ISSUE TITLE
GitHub cleanups

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#258]
Few small changes:

1. [x] Rename repository to `mobility-marketplace` or `mobi-mart` or similar
2. [x] Rename branch `master` -> `main`
3. [x] Delete the `dev` branch if we're no longer going to use it
4. [x] README should also be updated with any references to either Transit Stop or `master`.

FYI, this may impact the Netlify process and updates must be made there as well.

**Comment by thekaveman** [comment]
@krainboltgreene @allejo Can we please prioritize at least item 1 from this list for sometime next week 4/26-30? The naming is confusing to the non-tech folks in Cal-ITP that may need to submit Issues for us.

**Comment by allejo** [comment]
> Rename repository to `mobility-marketplace` or `mobi-mart` or similar

I tested out Netlify's behavior on renaming repos. It appears that as long as you have the Netlify GitHub app installed on the repo, renaming the repo won't have any effect.

![image](https://user-images.githubusercontent.com/1246453/118012028-7e4b3b00-b305-11eb-89b2-bffec2947281.png)

The only thing that doesn't get updated is the URL that's visible in the UI. For example, I've renamed this repo to "Web-BZEdit" (with a hyphen) but Netlify still shows the old URL. Clicking on this URL from the UI will redirect you to the new URL (GitHub takes care of the redirect)

![image](https://user-images.githubusercontent.com/1246453/118012071-8905d000-b305-11eb-9641-f0db3932e5a8.png)

![image](https://user-images.githubusercontent.com/1246453/118012127-96bb5580-b305-11eb-97ed-e23c70f4834e.png)

However, pushing new commits to the repo after it's been renamed still triggers builds and deployments successfully.

Renaming a repo won't break existing clones as GitHub will just notify you of the repo rename but still let you push.

![image](https://user-images.githubusercontent.com/1246453/118012876-5f00dd80-b306-11eb-92eb-12ade68ffba7.png)

---

> Rename branch `master` -> `main`

GitHub's got built-in functionality for this on the web UI: https://github.com/github/renaming#renaming-existing-branches.

This will "break" existing clones where the `master` branch won't get automatically renamed to `main` but that shouldn't really affect users on this repo since we don't really push directly to master anyways.

**Comment by allejo** [comment]
> Delete the `dev` branch if we're no longer going to use it

Deleted this branch, it was only used for #146 and has not received any activity since. I also disabled this branch on Netlify from making deployments.

If it's needed for the July updates, we can recreate it or come up with a better naming scheme for milestones.

**Comment by allejo** [comment]
> 2\. Rename branch `master` -> `main`

Renamed the branch on GitHub to `main` and have updated Netlify to use `main` as the production deployment branch. I've also triggered a manual re-deployment on Netlify and everything looks good :+1:

https://app.netlify.com/sites/cal-itp-transit-stop/deploys/60b57bad6a1bd934742f6112

---

Closing as completed
