### ISSUE TITLE
Add Connectivity contracts to table

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/mobility-marketplace#309]
**Updates:** 

We are still waiting on the First Net Contract but, in the meantime, can and should link to the products available on CalNet. The updates we want to make include:

- On /contracts page for the "Data Plans" products 
-- Link to https://cdt.ca.gov/services/calnet-calitp/ from "View Contracts" button
-- Add new icon (see attached)
-- Add new blurb: 

_**Data Plans**_
Fleet modernization and new vehicle technology are allowing us to be even more connected with our transit journeys. To do this, most require data access. The below data plans are available to agencies with the pre-negotiated rates listed.

- On /contracts/view page:
-- Add new row to table 
-- There is no Contract Number, we can just add "View" as the link, and link should go to https://cdt.ca.gov/services/calnet-calitp/
-- Category: Connectivity
-- Product: Data Plans 
-- Vendor: Verizon, AT&T, T-Mobile

**Comment by esquared415** [comment]
_This is the blurb we'd discussed back in Feb (see this [doc](https://docs.google.com/document/d/15K-x6jEzhjtUi8xLxs-JMQYHDEGu2CLF-e0YRzKEjzQ/edit#) and scroll down to Connectivity):_
Fleet modernization and new vehicle technology are allowing us to be even more connected with our transit journeys. To do this, most require data access. The below data plans are available to agencies with the pre-negotiated rates listed. 

_Beneath the blurb, we'd talked about 2 buttons instead of usual one:_
- MORE INFORMATION _(would link to a Mobi Mart webpage with contract info and graphics that are under "Connectivity" in above GDoc)_
- VIEW CONTRACTS _(links to /contracts/view)_

Can't tag Lauren in here; want to run all of the above by her, @mrose914?

**Comment by mlgilbert18** [comment]
Everything looks good to me! Thanks @mrose914 and @esquared415

**Comment by esquared415** [comment]
Thanks, all!

**Comment by segacy1** [comment]
[](url)
![connectivity](https://user-images.githubusercontent.com/33331853/191020431-f8f9fec6-e131-4917-a5a0-2b1228993099.svg)

Here's the icon!

**Comment by thekaveman** [comment]
@mrose914 I think we need to clarify one thing, but otherwise this all sounds doable in the next couple of weeks.

On the `/contracts` page, we'll have a new section (with the new icon) for *Data Plans*. The buttons in those sections are auto-generated to point to the `/contracts/view` page with an appropriate filter applied.

So the button in the new section on `/contracts` will point to the filtered table (the single row we'll add) on the `/contracts/view` table. From there, the user will be able to click the link to get to the CalNet page. The new row will also appear in the table when filters are removed and/or the user clicks the *View all contracts* link.

Does this make sense, and work for you?
