### ISSUE TITLE
Redirect /resources page to new /how-to/go-contactless

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#375]
The /resources page is not public, but we've shared it in various interactions with agencies and others. We'd like to redirect landing on /resources to the new /how-to-go-contactless page (once that page is live).

**Comment by thekaveman** [comment]
@machikoyasuda We also currently have a redirect FROM `https://resources.calitp.org` TO `https://camobilitymarketplace.org/resources`. 

Since the latter is going to be redirected to the Go Contactless page, we should cut out that extra hop, and also redirect `https://resources.calitp.org` to the new Go Contactless page. This is done via the `index.html` file sitting in the bucket.

**Comment by thekaveman** [comment]
Just to clarify here @mrose914 -- we no longer need the content on the resources page either, right? Since we'll just be redirecting to the new page, it doesn't make sense to maintain that (likely out of date) page...

**Comment by thekaveman** [comment]
One task is done: `resources.calitp.org` now redirects straight to the `/how-to/go-contactless` page instead of hopping through the intermediate `/resources` page (that we are going to also redirect)
