### ISSUE TITLE
SCOPE: Confirm tracking and analytics plan for MobiMart Contactless V2

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#395]
This is just a scoping ticket to make sure that we implement, as a quick follow on to the Contactless V2 release, analytics tracking. 

I have the following questions (I think I discussed with @thekaveman when we initially discussed this redesign but so much time has passed I want to confirm my understanding):

- Confirm that Google Analytics will automatically pick up and track page views of the new pages (/how-to-go-contactless) https://analytics.google.com/analytics/web/#/report/content-pages/a212080580w245681683p235484275/

- Confirm that the current tracking we have in Google Analytics on clicks into the resource documents does not need to be updated (https://analytics.google.com/analytics/web/#/report/content-event-events/a212080580w245681683p235484275/explorer-segmentExplorer.segmentId=analytics.eventLabel&_r.drilldown=analytics.eventCategory:downloads&explorer-table.plotKeys=%5B%5D)

- Confirm that we need to add something to track the new /how-to-go-contactless page in Amplitude so it shows up here? https://analytics.amplitude.com/compiler/chart/vkuwrzo?linkingDashboardId=agerz0x

**Comment by machikoyasuda** [comment]
Answers:

- **YES, will double-check after launch**. Confirm that Google Analytics will automatically pick up and track page views of the new pages (/how-to-go-contactless) https://analytics.google.com/analytics/web/#/report/content-pages/a212080580w245681683p235484275/
- **YES, will double-check after launch**. Confirm that the current tracking we have in Google Analytics on clicks into the resource documents does not need to be updated (https://analytics.google.com/analytics/web/#/report/content-event-events/a212080580w245681683p235484275/explorer-segmentExplorer.segmentId=analytics.eventLabel&_r.drilldown=analytics.eventCategory:downloads&explorer-table.plotKeys=%5B%5D)

- Double-checking: @thekaveman This https://github.com/cal-itp/mobility-marketplace/commit/f89ad80fe5486b0a473e0a4b3ef0023cc5be5e73 is tracking all clicks on the site, and sending it to Amplitude right?

I believe we do not need to add any code to get analytics for all the changes in this milestone.

**Comment by thekaveman** [comment]
**Amplitude**

Our Amplitude code is set up to [track clicks on every link](https://github.com/cal-itp/mobility-marketplace/blob/main/src/scripts/amplitude.js#L42). Since that script is [included on every page](https://github.com/cal-itp/mobility-marketplace/blob/main/src/_layouts/default.html#L87), Amplitude will always get all link clicks.

As @machikoyasuda noted, Amplitude also automatically tracks a pageview for every page too.

**Google Analytics**

* For pageviews, this happens automatically 
* For Resources `download` events, this has to be done manually per-link using the [`onclick` attribute of the `<a>` tag](https://github.com/cal-itp/mobility-marketplace/blob/main/src/resources.html#L35). Existing resource links will continue to work, even if the underlying PDFs are updated. New links added to that page would need the `onclick` treatment applied. We can look at automating this for all `resources.calitp.org` links in a future sprint.

**Comment by machikoyasuda** [comment]
@mrose914 yes please create a new ticket
