### ISSUE TITLE
Develop new Hubspot forms for /contact page

### ISSUE THREAD

**Issue by mrose914** [cal-itp/mobility-marketplace#424]
We will create 3 forms for us on the new /contact page. Approved questions/answers and field types are here: https://docs.google.com/spreadsheets/d/1kHrvfI0pa3NFvLa63JvM1zl9gyxJET5Bxn9sxoHEj6c/edit#gid=2006638120

**Comment by thekaveman** [comment]
This is being tracked in the CRM repo under https://github.com/cal-itp/crm-helpdesk/issues/193

**Comment by AnthonyRollins** [comment]
@mrose914 We completed the forms based on the approved [questions/answers spreadsheet](https://docs.google.com/spreadsheets/d/1kHrvfI0pa3NFvLa63JvM1zl9gyxJET5Bxn9sxoHEj6c/edit#gid=2006638120). Here are the preview links for all the forms, please take a look and let me know if you have any questions.

- [Transit Agency Form Preview](https://share.hsforms.com/1Rn583AtVTw2zbz9rHz0Zqw3aanu)
- [Vendor Form Preview](https://share.hsforms.com/13iLWkBhPQE23h28z6ZOzmQ3aanu)
- [Other Form Preview](https://share.hsforms.com/1EO0HDkLERFG1R6YmgSPMgA3aanu)

For the development, see the embed code for all three forms.

Transit Agency Form
```
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/embed/v2.js"></script>
<script>
  hbspt.forms.create({
    region: "na1",
    portalId: "5519226",
    formId: "467e7cdc-0b55-4f0d-b36f-3f6b1f3d19ab"
  });
</script>
```
Vendor Form
```
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/embed/v2.js"></script>
<script>
  hbspt.forms.create({
    region: "na1",
    portalId: "5519226",
    formId: "de22d690-184f-404d-b787-6f33e993b399"
  });
</script>
```
Other Form
```
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/embed/v2.js"></script>
<script>
  hbspt.forms.create({
    region: "na1",
    portalId: "5519226",
    formId: "10ed070e-42c4-4451-b547-a6268123cc80"
  });
</script>
```

**Comment by o-ram** [comment]
No objections from me! I've tagged Erika in slack since we approved these together just to make sure she has no objections either.

**Comment by machikoyasuda** [comment]
@AnthonyRollins Not sure if this is a Hubspot design thing or not, but I noticed that some of the fields are in 2 columns. Forms in 1 column designs are found to be better accessibility and better user experience than 2. The embed and HTML shows up this way too:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/3673236/221687938-53cbbb18-2da3-4913-a518-be4cf55f077a.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/221688146-aa654de0-dcd2-46bc-9135-6a5aa34520e8.png">

Could you go into Hubspot and change these 2-column fields so that each field shows up in its own line, like this:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/3673236/221688382-74065441-df91-491f-a4ce-06211d8200a3.png">

**Comment by AnthonyRollins** [comment]
@machikoyasuda All forms have been updated to a single column. Let me know if that works.
